import type { Metadata } from 'next';
import './globals.scss';
import LenisProvider from './components/LenisProvider';

export const metadata: Metadata = {
    title: 'Xyntium Finances',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <LenisProvider />
                {children}
            </body>
        </html>
    );
}
